package com.bmapp.api.ui.model.response;
// Generated 21-jul-2021 17:27:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Expenses generated by hbm2java
 */
public class ChartDataResponseModel  implements java.io.Serializable {
     
     private String month;
     private Double amount;
     

    public ChartDataResponseModel() {
    }

    public ChartDataResponseModel(String month, Double amount) {
        this.month = month;
        this.amount = amount;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

   


}


