package com.bmapp.api.ui.model.response;
// Generated 21-jul-2021 17:27:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Expenses generated by hbm2java
 */

// Modelo utilizado para enviar los datos de los gastos al usuario
public class ExpensesDetailsResponseModel  implements java.io.Serializable {


     private Integer expenseId;
     private String expenseDate;
     private Double amount;
     private String type;
     private String description;

    public ExpensesDetailsResponseModel() {
    }

    public ExpensesDetailsResponseModel(Integer expenseId, String expenseDate, Double amount, String type, String description) {
        this.expenseId = expenseId;
        this.expenseDate = expenseDate;
        this.amount = amount;
        this.type = type;
        this.description = description;
    }

    
   
    public Integer getExpenseId() {
        return this.expenseId;
    }
    
    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }
   
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
   
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getExpenseDate() {
        return expenseDate;
    }

    public void setExpenseDate(String expenseDate) {
        this.expenseDate = expenseDate;
    }




}


