package com.bmapp.api;
// Generated 21-jul-2021 17:27:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Expenses generated by hbm2java
 */

// Modelo que representa la tabla de gastos
public class Expenses  implements java.io.Serializable {

     private Integer expenseId;
     private Date expenseDate;
     private Double amount;
     private Integer userId;
     private String type;
     private String description;

    public Expenses() {
    }
    

    public Expenses(Date expenseDate, Double amount, Integer userId, String type, String description) {
       this.expenseDate = expenseDate;
       this.amount = amount;
       this.userId = userId;
       this.type = type;
       this.description = description;
    }
   
    public Integer getExpenseId() {
        return this.expenseId;
    }
    
    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }
    public Date getExpenseDate() {
        return this.expenseDate;
    }
    
    public void setExpenseDate(Date expenseDate) {
        this.expenseDate = expenseDate;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


