package com.bmapp.api;
// Generated 21-jul-2021 17:27:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */

// Modelo que representa la tabla de usuarios
public class Users  implements java.io.Serializable {

     private Integer userId;
     private String username;
     private String email;
     private String password;
     private Date startDate;

    public Users() {
    }

    public Users(String username, String email, String password, Date startDate) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.startDate = startDate;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }




}


